<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Error 409 User already existsError 409 _ac7751</name>
   <tag></tag>
   <elementGuidId>7d3f5ae5-d46a-41c4-beef-506c7e8d0716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#root</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>468bd601-81af-48d0-9c84-73919982100c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>33655c67-9761-4ccf-8ce8-f4a149401ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full</value>
      <webElementGuid>8daf4c49-050f-4d66-bee3-50d55029ce1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsAlready have an account? Sign in now!</value>
      <webElementGuid>97fefed3-f7a1-4ae7-8b47-ade74b7cbe5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)</value>
      <webElementGuid>10950417-8902-4614-badc-23f97d8510ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='root']</value>
      <webElementGuid>5108061b-d618-4d3f-badc-e91de04854b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>ba76b514-cd5f-4dfd-a01c-8b6ac4e6f988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'root' and (text() = 'Error 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsAlready have an account? Sign in now!' or . = 'Error 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsAlready have an account? Sign in now!')]</value>
      <webElementGuid>95b5ffa6-6531-40e4-87b0-d640ec19cbc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
