<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Error 409 User already existsError 409 _614745</name>
   <tag></tag>
   <elementGuidId>0e163914-bfe8-4421-bdf7-90b13e886d42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#root</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f69ee84c-08c9-4443-8fcf-06777dee499d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>f2aab4a5-14db-4c35-9998-1c5a3779aff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full</value>
      <webElementGuid>9113e118-1b9d-4065-99b5-e21cda208bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsForgot Password?Need an account? Register now!</value>
      <webElementGuid>ac4d6607-a2bd-4e51-b1ec-d9d0da7cdc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)</value>
      <webElementGuid>af7f8aea-291b-4dd0-8d08-a692abcc481a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='root']</value>
      <webElementGuid>7476c96b-4a38-47c5-8ab4-a94ffdbed961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>b08eb918-1d57-48d1-a6e4-1406532b379b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'root' and (text() = 'Error 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsForgot Password?Need an account? Register now!' or . = 'Error 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsError 409: User already existsForgot Password?Need an account? Register now!')]</value>
      <webElementGuid>5fab2208-b655-4d3d-9bc1-d5272891bea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
