<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Error 409 User already existsError 409 _78b110</name>
   <tag></tag>
   <elementGuidId>ba2b4e4c-3500-4d64-88ca-dcb9f08b5001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#root</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ce087023-6672-4e21-88e5-abe352a55394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>93e427ca-a275-4e0e-80bb-5eec0cdb4cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full</value>
      <webElementGuid>9ec98fc3-7be6-4a24-a1e5-57bd7271245e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error 409: User already existsError 409: User already existsError 409: User already existsAlready have an account? Sign in now!</value>
      <webElementGuid>4dd753ce-03ad-4eae-8c2d-ed0c05845e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)</value>
      <webElementGuid>0d58901b-ff5d-47da-9ddd-bc848371e943</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='root']</value>
      <webElementGuid>b7168421-c4a8-4f59-85ea-29d2865d0004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>7bd82539-bc70-4eb2-996c-bf106e5d5d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'root' and (text() = 'Error 409: User already existsError 409: User already existsError 409: User already existsAlready have an account? Sign in now!' or . = 'Error 409: User already existsError 409: User already existsError 409: User already existsAlready have an account? Sign in now!')]</value>
      <webElementGuid>790e17ba-8077-4628-a881-8a255b26528d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
