<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Books_1</name>
   <tag></tag>
   <elementGuidId>d102f675-85b1-4cb4-a17c-6a9c00f0c508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/header/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.font-semibold.px-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Books&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>da9b317a-d8ba-43ac-929c-f34e364e8a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/books</value>
      <webElementGuid>7113c94e-027f-4df2-853e-3c47c28cd108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-semibold px-5</value>
      <webElementGuid>2e4c7c60-4c0a-46f0-b165-446891a89524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Books</value>
      <webElementGuid>3c5707df-9fd3-40f8-bc2f-389c212091a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-[1420px] mx-auto&quot;]/div[@class=&quot;flex flex-col h-full&quot;]/header[@class=&quot;bg-white shadow-md&quot;]/div[@class=&quot;flex justify-between mb-6 w-full h-12 align-center&quot;]/div[@class=&quot;flex gap-3 items-center&quot;]/a[@class=&quot;font-semibold px-5&quot;]</value>
      <webElementGuid>de2fec3c-5d0b-48c9-a8dc-87e029ec3ed0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/header/div/div/a</value>
      <webElementGuid>f7090efc-0b9e-4caf-aa8e-0a6189e29a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Books')]</value>
      <webElementGuid>21491c64-a992-43d8-a751-f4cd408c3cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/preceding::a[1]</value>
      <webElementGuid>5923e39e-a959-4142-ba86-20073989bdac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Following'])[1]/preceding::a[2]</value>
      <webElementGuid>e8d5e3b8-e081-49fb-b693-dc6dc06c8003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Books']/parent::*</value>
      <webElementGuid>3548b1db-e5ee-456e-9a5a-5a3c29b8a8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/books')]</value>
      <webElementGuid>a5f97cb1-421e-4dde-99cf-16474f8f5675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>8e3601cd-9c89-4494-beec-4bb68552e0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/books' and (text() = 'Books' or . = 'Books')]</value>
      <webElementGuid>4b9213f5-3163-49c0-bc03-f73bebfb0378</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
