<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FollowingSeapeasdodinhhai29904gmail.com</name>
   <tag></tag>
   <elementGuidId>56218913-ac02-4607-8735-87d9a7b3167e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.w-full.border-r.border-gray-200.p-4.shadow-md.border-2.rounded-lg > div.mb-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;FollowingSeapeasdodinhhai29904@gmail.com&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8fd2b986-b1d3-4541-b9e1-e53ccf5c8b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-6</value>
      <webElementGuid>8ace3a37-6314-4e64-85f9-388fba830670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FollowingSeapeasdodinhhai29904@gmail.com</value>
      <webElementGuid>f7afab9b-279a-490d-980d-8e8999b1a576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-full p-10 h-full&quot;]/div[@class=&quot;grid grid-cols-4 mt-6 gap-4&quot;]/div[@class=&quot;col-start-1 col-span-1&quot;]/div[@class=&quot;w-full border-r border-gray-200 p-4  shadow-md border-2 rounded-lg&quot;]/div[@class=&quot;mb-6&quot;]</value>
      <webElementGuid>ecf13bd4-0e38-4f9b-96df-7b12e79b6487</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div/div</value>
      <webElementGuid>a51bacac-4be2-480f-a2da-6e42189656cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Following'])[1]/following::div[7]</value>
      <webElementGuid>0a32d967-2a43-409e-b44d-fe6cf2459dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/following::div[7]</value>
      <webElementGuid>5b3a15b4-3473-4242-9498-724e646e616c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>66cb5e1d-e740-49d9-98f9-7e20b4eab984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'FollowingSeapeasdodinhhai29904@gmail.com' or . = 'FollowingSeapeasdodinhhai29904@gmail.com')]</value>
      <webElementGuid>4e928130-ea6a-4837-83d4-bb220b2d0daa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
