<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Seapeas</name>
   <tag></tag>
   <elementGuidId>ce8dcb72-4ccc-4464-902f-74f50b9e5486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div/div/div/div[2]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Seapeas dodinhhai29904@gmail.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9d546e25-3a56-46df-9841-76c66e4481dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-left</value>
      <webElementGuid>9fc1a3f2-2ccc-499b-8fc3-e6b10de5f70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seapeas</value>
      <webElementGuid>3cb28054-0f08-4414-8cfb-953ed15d4cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-full p-10 h-full&quot;]/div[@class=&quot;grid grid-cols-4 mt-6 gap-4&quot;]/div[@class=&quot;col-start-1 col-span-1&quot;]/div[@class=&quot;w-full border-r border-gray-200 p-4  shadow-md border-2 rounded-lg&quot;]/div[@class=&quot;mb-6&quot;]/div[@class=&quot;ml-7 space-y-2&quot;]/a[1]/div[@class=&quot;text-left&quot;]</value>
      <webElementGuid>ac467c11-0b52-4a4f-9bf9-28206f089e64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div/div/div[2]/a/div</value>
      <webElementGuid>58cb4c56-0d29-4b81-9e7e-87a4f6d7b9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Following'])[2]/following::div[2]</value>
      <webElementGuid>8d59280e-9405-4811-b934-c08afc684760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Following'])[1]/following::div[10]</value>
      <webElementGuid>1292f1d3-3297-4855-b532-1bc0911cd3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dodinhhai29904@gmail.com'])[1]/preceding::div[1]</value>
      <webElementGuid>5de0ec1e-0f49-444c-85e4-0fb49103daf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seapeas']/parent::*</value>
      <webElementGuid>38ea3a10-633c-46fd-9d91-dcd80dce0ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>562de5e1-ea83-4ea6-9134-f5a32ede38ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Seapeas' or . = 'Seapeas')]</value>
      <webElementGuid>1e6b93fd-19d5-4b68-8499-504d8172f56e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
