<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BooksMy ProfileFollowing</name>
   <tag></tag>
   <elementGuidId>7a785ecc-f1e5-4fa6-b9ba-0c3c810d3853</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.gap-3.items-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;BooksMy ProfileFollowing&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b938b93-7840-41c5-8fe3-1515d6050145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex gap-3 items-center</value>
      <webElementGuid>16269b44-0570-4fd6-9705-ced1dfe85103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BooksMy ProfileFollowing</value>
      <webElementGuid>c36f1752-2191-4e30-987e-5490b321a929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-full p-10 h-full&quot;]/div[@class=&quot;flex justify-between mb-6 w-full h-12 align-center&quot;]/div[@class=&quot;flex gap-3 items-center&quot;]</value>
      <webElementGuid>b186d918-954e-43d5-802c-bf74d1e8d210</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div</value>
      <webElementGuid>3e6d900e-7ddd-4c82-9a92-9bcee4fbec0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>5a4a4a2f-9e5b-41ab-8bac-addd29568a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'BooksMy ProfileFollowing' or . = 'BooksMy ProfileFollowing')]</value>
      <webElementGuid>8bbcbd78-cde2-4440-9a6b-410f66db5cc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
