<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_phamtranyenquyengmail.com</name>
   <tag></tag>
   <elementGuidId>f1a22117-63d2-4a66-b137-9e95beae80ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/main/div/div[2]/header/div/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.text-sm.text-gray-600</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;phamtranyenquyen@gmail.com&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c6c6de7d-d1c4-427d-842a-2728efa27c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-gray-600</value>
      <webElementGuid>667fa374-3ae8-47a8-a6d1-42d31ce8665d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>phamtranyenquyen@gmail.com</value>
      <webElementGuid>f0e2506b-80a5-4980-834e-32d7584d50ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-[1420px] mx-auto&quot;]/div[@class=&quot;flex flex-col h-full&quot;]/main[@class=&quot;flex-grow overflow-y-auto&quot;]/div[@class=&quot;flex h-screen mx-auto my-0&quot;]/div[@class=&quot;flex-grow bg-gray-50&quot;]/header[@class=&quot;bg-green-100 p-4 flex justify-between items-center&quot;]/div[@class=&quot;flex items-center gap-4&quot;]/div[2]/p[@class=&quot;text-sm text-gray-600&quot;]</value>
      <webElementGuid>bb97da6e-19c1-482b-9b1e-97368f3b97a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/main/div/div[2]/header/div/div[2]/p</value>
      <webElementGuid>79c2025f-6367-42ec-89e0-14b4f3e8a022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='roke'])[1]/following::p[1]</value>
      <webElementGuid>ec830c83-adea-4728-8aab-214d11720342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Following'])[1]/following::p[1]</value>
      <webElementGuid>623ac0d7-d9e4-4e54-af69-4bfe2d9b19dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Management'])[1]/preceding::p[1]</value>
      <webElementGuid>2455b557-e46e-453b-9862-3d8d2b482243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::p[1]</value>
      <webElementGuid>2510a3ca-e341-420d-9247-fd4b65a36c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='phamtranyenquyen@gmail.com']/parent::*</value>
      <webElementGuid>b4300187-0f20-442f-9ef9-a04fbaed0421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>86a69be7-15fe-4dcf-920d-740be40a6503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'phamtranyenquyen@gmail.com' or . = 'phamtranyenquyen@gmail.com')]</value>
      <webElementGuid>197bd6e7-4c12-4762-8741-061570a5c1a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
